import Head from 'next/head'
import AwsClouldSVG from './svgComponents/cloud'
import Windmill from './svgComponents/windmill'
import { useRef } from 'react'
import ToggleButton from './components/toggleButton'
import MyModal from './components/modal'
import Bike from './svgComponents/bike'
import Cloud1 from './svgComponents/cloud1'
import Cloud2 from './svgComponents/cloud2'
import Cloud3 from './svgComponents/cloud3'
import Cloud4 from './svgComponents/cloud4'
import Moon from './svgComponents/moon'
import dynamic from 'next/dynamic'
const LazyLoadSnowfall = dynamic(
  () => import('./components/lazyLoadSnowfall'),
  {
    loading: () => <header />,
  }
)

export default function Home() {
  const main = useRef<HTMLHeadingElement>(null)
  return (
    <div>
      <Head>
        <title>Greetings Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main ref={main} id="main" className="dark">
        <div
          className={
            'max-w-screen relative overflow-hidden h-screen w-screen max-h-screen bg-cover xl:bg-bottom bg-right bg-[url("/background.svg")] dark:bg-[url("/darkBackground.svg")]'
          }
        >
          <LazyLoadSnowfall />
          <div className="flex justify-center ">
            <ToggleButton
              onClick={() => main.current?.classList.toggle('dark')}
            />
          </div>
          <Moon
            cssClass={
              'hidden dark:inline animate-moon w-[25%] xl:hover:w-[26%]'
            }
          />
          {/* <AwsClouldSVG
         
          cssClass={"animate-could1 w-[25%] xl:hover:w-[26%]"}
        /> */}
          <Cloud1 cssClass={'animate-could1 w-[25%] xl:hover:w-[26%]'} />
          <Cloud2 cssClass={'animate-could2 w-[25%] xl:hover:w-[26%]'} />
          <Cloud3 cssClass={'animate-could3 w-[25%] xl:hover:w-[26%]'} />
          <Cloud4 cssClass={'animate-could4 w-[25%] xl:hover:w-[26%]'} />
          <div className="absolute flex bottom-[25%] right-4 lg:right-0 lg:left-8 h-[20%]">
            <Windmill />
            <Windmill hideOnMobile={true} />
            <Windmill hideOnMobile={true} />
          </div>

          <div className="h-[12%] absolute bottom-0 left-0">
            <Bike />
          </div>
        </div>
      </main>
    </div>
  )
}
